"""Strategy generation routes."""

from __future__ import annotations

import threading
from typing import Optional

from fastapi import APIRouter, HTTPException, BackgroundTasks, Query
from datetime import datetime

from ..schemas import (
    StrategyRequest,
    StrategyResponse,
    StrategyResult,
    ScenarioType,
)
from ..job_manager import JobManager, JobStatus
from ...agents import (
    MSCIMAgent,
    CMFBEAgent,
    KnowledgeBaseAgent,
    AquaTurbGPTAgent,
    RLTGRRAgent,
    SafetyAgent,
)
from ...orchestrator.coordinator import Orchestrator

# Global job manager
job_manager = JobManager()

router = APIRouter(prefix="/api", tags=["strategy"])


def _execute_strategy(
    job_id: str,
    scenario: str,
    state: dict,
    episodes: int,
    backend: str,
    knowledge_context: Optional[dict] = None,
) -> None:
    """Background task to execute strategy generation.

    ``knowledge_context`` is the graph evidence the platform retrieved for this
    request. It is threaded through to the orchestrator rather than merged into
    ``state`` because ``state`` is indexed by feature name downstream. Absent
    (the default, and what every caller sends unless it opted in) means the
    knowledge base answers from its curated dictionary exactly as before.
    """
    try:
        # Update status to running
        job_manager.update_job_status(job_id, JobStatus.RUNNING)
        job_manager.set_stage(job_id, "input")

        # Initialize components
        agents = {
            "MSCIMAgent": MSCIMAgent(),
            "CMFBEAgent": CMFBEAgent(),
            "KnowledgeBaseAgent": KnowledgeBaseAgent(),
            "AquaTurbGPTAgent": AquaTurbGPTAgent(
                config={"deepseek": {"backend": backend}}
            ),
            "RLTGRRAgent": RLTGRRAgent(),
            "SafetyAgent": SafetyAgent(),
        }

        orchestrator = Orchestrator()

        # Run orchestrator with stage callbacks
        def on_stage(stage_name: str):
            job_manager.set_stage(job_id, stage_name)

        result = orchestrator.run(
            agents,
            state,
            scenario_key=scenario,
            on_stage=on_stage,
            knowledge_context=knowledge_context,
        )

        # Prepare result
        strategy_result = {
            "job_id": job_id,
            "scenario": scenario,
            "strategy": result.get("safe_action", {}),
            "metrics": result.get("metrics", {}),
            "reasoning_viz_path": result.get("planning", {})
            .get("strategy", {})
            .get("reasoning_viz_path"),
            "episodes": episodes,
            "agent_traces": result.get("agent_traces", {}),
        }

        job_manager.set_stage(job_id, "done")
        # Update job as completed
        job_manager.update_job_status(
            job_id,
            JobStatus.COMPLETED,
            result=strategy_result,
        )

    except Exception as e:
        # Update job as failed
        job_manager.update_job_status(
            job_id,
            JobStatus.FAILED,
            error=str(e),
        )


@router.post("/strategy", response_model=StrategyResponse)
async def generate_strategy(
    request: StrategyRequest,
    background_tasks: BackgroundTasks,
) -> StrategyResponse:
    """Generate water quality management strategy.
    
    This endpoint receives water quality measurements and returns
    a strategy generated by the multi-agent system.
    
    Args:
        request: Strategy request with scenario and water quality state
        background_tasks: FastAPI background tasks
        
    Returns:
        StrategyResponse with job ID and status
    """
    # Create job
    job_id = job_manager.create_job(
        scenario=request.scenario.value,
        state=request.state.model_dump(),
        episodes=request.episodes,
        backend=request.backend,
        request_id=request.request_id,
    )
    
    # Schedule background execution
    background_tasks.add_task(
        _execute_strategy,
        job_id=job_id,
        scenario=request.scenario.value,
        state=request.state.model_dump(),
        episodes=request.episodes,
        backend=request.backend,
        knowledge_context=(
            request.knowledge_context.model_dump()
            if request.knowledge_context is not None
            else None
        ),
    )
    
    return StrategyResponse(
        job_id=job_id,
        status=JobStatus.QUEUED,
        scenario=request.scenario.value,
        message=f"Strategy generation queued. Job ID: {job_id}",
    )


@router.get("/strategy/{job_id}", response_model=StrategyResult)
async def get_strategy_result(job_id: str) -> StrategyResult:
    """Get strategy generation result.
    
    Args:
        job_id: Job identifier
        
    Returns:
        Strategy result with full details
        
    Raises:
        HTTPException: If job not found
    """
    job = job_manager.get_job(job_id)
    
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
    
    result = job.get("result") or {}
    
    return StrategyResult(
        job_id=job_id,
        scenario=job["scenario"],
        status=job["status"],
        strategy=result.get("strategy", {}),
        metrics=result.get("metrics", {}),
        agent_traces=result.get("agent_traces", {}),
        reasoning_viz_path=result.get("reasoning_viz_path"),
        error=job.get("error"),
        completed_at=(
            datetime.fromisoformat(job["completed_at"])
            if job.get("completed_at")
            else None
        ),
    )


@router.get("/strategy/{job_id}/stage")
async def get_job_stage(job_id: str) -> dict:
    """Get current processing stage of a job."""
    job = job_manager.get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
    return {
        "job_id": job_id,
        "status": job["status"],
        "stage": job.get("current_stage", "queued"),
    }


@router.get("/jobs", response_model=list[dict])
async def list_jobs(
    status: Optional[str] = Query(None),
    scenario: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=1000),
) -> list[dict]:
    """List all jobs with optional filtering.
    
    Args:
        status: Filter by status (queued, running, completed, failed)
        scenario: Filter by scenario
        limit: Maximum number of jobs to return
        
    Returns:
        List of job summaries
    """
    status_enum = JobStatus(status) if status else None
    
    jobs = job_manager.list_jobs(
        status=status_enum,
        scenario=scenario,
        limit=limit,
    )
    
    # Return simplified job info
    return [
        {
            "job_id": j["job_id"],
            "scenario": j["scenario"],
            "status": j["status"],
            "created_at": j["created_at"],
            "completed_at": j.get("completed_at"),
            "has_error": j.get("error") is not None,
        }
        for j in jobs
    ]


@router.delete("/jobs/{job_id}", response_model=dict)
async def cancel_job(job_id: str) -> dict:
    """Cancel a job (only if not already running or completed).
    
    Args:
        job_id: Job identifier
        
    Returns:
        Cancellation result
    """
    job = job_manager.get_job(job_id)
    
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
    
    current_status = job["status"]
    
    if current_status in (JobStatus.COMPLETED, JobStatus.FAILED):
        raise HTTPException(
            status_code=400,
            detail=f"Cannot cancel job with status {current_status}",
        )
    
    job_manager.update_job_status(job_id, JobStatus.CANCELLED)
    
    return {
        "job_id": job_id,
        "status": JobStatus.CANCELLED,
        "message": f"Job {job_id} cancelled",
    }
