#!/usr/bin/env bash
# One-time (idempotent) production bootstrap on the ECS, run from the maintainer
# machine as root (key auth). Creates the deploy layout, Python venvs, .env
# secrets, systemd units and the nginx reverse proxy. Heavy `pip install` of the
# platform venv is NOT done here — run `--with-deps` once, or install manually,
# because it is long and you want to watch it.
#
#   ./scripts/deploy/bootstrap_server.sh            # layout + .env + units + nginx
#   ./scripts/deploy/bootstrap_server.sh --with-deps # also create venvs + pip install
#
# Env overrides: OPERATOR_USER, OPERATOR_PASS (defaults generated & printed once),
# PUBLIC_IP (nginx/CORS origin), HOST.
set -euo pipefail

HOST="${HOST:-root@47.84.185.231}"
PUBLIC_IP="${PUBLIC_IP:-47.84.185.231}"
OPERATOR_USER="${OPERATOR_USER:-operator}"
OPERATOR_PASS="${OPERATOR_PASS:-$(openssl rand -hex 12)}"
JWT_SECRET="$(openssl rand -hex 32)"
WITH_DEPS=0
for arg in "$@"; do
  [ "$arg" = "--with-deps" ] && WITH_DEPS=1
done

echo ">> Bootstrapping $HOST"
echo ">> Operator account:  $OPERATOR_USER"
echo ">> Operator password: $OPERATOR_PASS   <-- printed once; store it safely"
echo ">> Public IP (nginx/CORS): $PUBLIC_IP"

ssh -o BatchMode=yes "$HOST" \
  "OPERATOR_USER='$OPERATOR_USER' OPERATOR_PASS='$OPERATOR_PASS' JWT_SECRET='$JWT_SECRET' PUBLIC_IP='$PUBLIC_IP' WITH_DEPS='$WITH_DEPS' bash -s" <<'REMOTE'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

echo "[bootstrap] layout"
install -d -o waterexpert -g waterexpert /srv/waterexpert /srv/waterexpert/app /srv/waterexpert-agent

echo "[bootstrap] platform venv"
if [ ! -x /srv/waterexpert/venv/bin/python ]; then
  sudo -H -u waterexpert python3.12 -m venv /srv/waterexpert/venv
fi

echo "[bootstrap] platform .env"
if [ ! -f /srv/waterexpert/app/.env ]; then
  cat > /srv/waterexpert/app/.env <<ENVF
# Generated by bootstrap_server.sh on $(date -u +%F). Root-owned; never commit.
WATEREXPERT_JWT_SECRET=$JWT_SECRET
WATEREXPERT_DEMO_USERNAME=$OPERATOR_USER
WATEREXPERT_DEMO_PASSWORD=$OPERATOR_PASS
WATEREXPERT_DEMO_EMAIL=operator@waterexpert.local
WATEREXPERT_DEMO_ROLE=admin
WATEREXPERT_ENABLE_REGISTRATION=0
WATEREXPERT_ENABLE_DEMO_HINT=0
WATEREXPERT_MAX_CONCURRENT_JOBS=1
WATEREXPERT_AGENT_API_URL=http://127.0.0.1:8001/api
WATEREXPERT_CORS_ORIGINS=http://$PUBLIC_IP
# Optional, unset by default (features degrade gracefully per docs):
# WATEREXPERT_KG_LLM_API_KEY=
# WATEREXPERT_REALTIME_APPCODE=
# WATEREXPERT_NOTIFICATION_WEBHOOK=
ENVF
  chmod 600 /srv/waterexpert/app/.env
  chown root:root /srv/waterexpert/app/.env
fi

echo "[bootstrap] systemd units"
cat > /etc/systemd/system/waterexpert-platform.service <<'UNIT'
[Unit]
Description=WaterExpert platform (FastAPI + static /ui)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=waterexpert
Group=waterexpert
WorkingDirectory=/srv/waterexpert/app
EnvironmentFile=/srv/waterexpert/app/.env
Environment=PYTHONUNBUFFERED=1
# Single-process scheduler: never add --workers or gunicorn (see .env.example).
ExecStart=/srv/waterexpert/venv/bin/python -m uvicorn backend.app.main:app --host 127.0.0.1 --port 8000
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/waterexpert-agent.service <<'UNIT'
[Unit]
Description=WaterExpert Water AI agent API (co-deployed, loopback only)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=waterexpert
Group=waterexpert
WorkingDirectory=/srv/waterexpert-agent
EnvironmentFile=/srv/waterexpert-agent/.env
Environment=PYTHONUNBUFFERED=1
ExecStart=/srv/waterexpert-agent/venv/bin/python scripts/run_api_server.py --host 127.0.0.1 --port 8001
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
UNIT

echo "[bootstrap] nginx reverse proxy (HTTP :80 -> :8000)"
cat > /etc/nginx/sites-available/waterexpert.conf <<'NGX'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    client_max_body_size 700m;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }
}
NGX
ln -sf /etc/nginx/sites-available/waterexpert.conf /etc/nginx/sites-enabled/waterexpert.conf
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl enable nginx >/dev/null 2>&1 || true
systemctl reload nginx || systemctl restart nginx

echo "[bootstrap] daemon-reload"
systemctl daemon-reload

if [ "$WITH_DEPS" = 1 ]; then
  echo "[bootstrap] pip install platform requirements (long)..."
  sudo -H -u waterexpert /srv/waterexpert/venv/bin/pip install --upgrade pip >/dev/null
  sudo -H -u waterexpert /srv/waterexpert/venv/bin/pip install -r /srv/waterexpert/app/requirements.txt
  echo "[bootstrap] platform deps installed."
fi

echo "[bootstrap] done"
REMOTE

echo ">> Bootstrap complete for $HOST"
echo ">> Next: release.sh --scope=platform --skip-checks  (ship code + frontend/out)"
